/*
 * Copyright (c) 2026, Jack Hartnett
 * All rights reserved.
 *
 * BSD-2-Clause. See LICENSE.
 */
package com.betterobjecthider;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import lombok.extern.slf4j.Slf4j;

/**
 * The OSRS world map's own text labels — the place names Jagex draws on the
 * in-game map, with exact world coordinates — loaded once from
 * {@code map_labels.tsv} (generated by the {@code dumpMapLabels} dev task from
 * the game cache; static factual geography, nothing is read at runtime beyond
 * the bundled file). Labels are points, so lookup is nearest-within-radius;
 * plane is stored but not matched (underground areas live in their own x/y
 * coordinate space, so there are no meaningful collisions).
 */
@Slf4j
public final class MapLabels
{
	private static final List<Label> LABELS = load();

	static final class Label
	{
		final int x;
		final int y;
		final int plane;
		final String name;

		Label(int x, int y, int plane, String name)
		{
			this.x = x;
			this.y = y;
			this.plane = plane;
			this.name = name;
		}
	}

	private MapLabels()
	{
	}

	/**
	 * @return the name of the closest label within {@code maxDistance} tiles
	 *         (Chebyshev) of the world point, or null when none is near enough
	 */
	public static String nearest(int worldX, int worldY, int maxDistance)
	{
		return nearest(LABELS, worldX, worldY, maxDistance);
	}

	static String nearest(List<Label> labels, int x, int y, int maxDistance)
	{
		String best = null;
		int bestDistance = maxDistance + 1;
		for (final Label label : labels)
		{
			final int distance = Math.max(Math.abs(label.x - x), Math.abs(label.y - y));
			if (distance < bestDistance)
			{
				bestDistance = distance;
				best = label.name;
			}
		}
		return best;
	}

	/** All loaded labels; read-only, for tests. */
	static List<Label> labels()
	{
		return LABELS;
	}

	/** @return the parsed label, or null when the line is a comment, blank, or malformed */
	static Label parseLine(String line)
	{
		if (line == null || line.isEmpty() || line.charAt(0) == '#')
		{
			return null;
		}
		final String[] fields = line.split("\t");
		if (fields.length < 4)
		{
			return null;
		}
		try
		{
			final int x = Integer.parseInt(fields[0].trim());
			final int y = Integer.parseInt(fields[1].trim());
			final int plane = Integer.parseInt(fields[2].trim());
			final String name = fields[3].trim();
			return name.isEmpty() ? null : new Label(x, y, plane, name);
		}
		catch (NumberFormatException ex)
		{
			return null;
		}
	}

	private static List<Label> load()
	{
		final List<Label> labels = new ArrayList<>();
		try (InputStream in = MapLabels.class.getResourceAsStream("map_labels.tsv"))
		{
			if (in == null)
			{
				log.warn("map_labels.tsv missing");
				return Collections.emptyList();
			}
			final BufferedReader reader = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
			String line;
			while ((line = reader.readLine()) != null)
			{
				final Label label = parseLine(line);
				if (label != null)
				{
					labels.add(label);
				}
			}
		}
		catch (IOException ex)
		{
			log.warn("failed to load map labels", ex);
		}
		return labels;
	}
}
